version: '3.4'
services:
    neog22bot-dev:
        container_name: neog22bot-dev
        env_file: dev.env
        image: neog22bot-dev:latest
        volumes:
            - ./logs:/app/logs
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start
    neog22bot-prod:
        container_name: neog22bot-prod
        env_file: .env
        image: neog22bot:latest
        volumes:
            - ./logs:/app/logs
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start
