name: Deploy Azure
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploying to Azure
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd neog22Bot
                      git checkout master
                      git pull
                      sudo npm run-script build 
                      sudo npm run-script run
